security:
        basic:
                enabled: false

management:
        security:
                enabled: false

 logging:
         level:
                 io: 
                    pitvotal: DEBUG

